REDIS_HOST: "localhost"
ES_HOST: "localhost"
MEMCACHE_HOST: "localhost"

POSTGRES_DB_HOST: "localhost"
POSTGRES_DB_USER: "geo_rails"
POSTGRES_DB_PASSWORD: "123456"
POSTGRES_DB_SU_USER: "su_geo_rails"
POSTGRES_DB_SU_PASSWORD: "123456"

development:
  POSTGRES_DB_NAME: "food_mate_production"
  POSTGRES_TEST_DB_NAME: "tinyowl_test"

test:
  POSTGRES_TEST_DB_NAME: "food_mate_test"

production:
  POSTGRES_DB_NAME: "food_mate_production"